const combinedFoodDatabase = [
  // Subway items
  {
  name: "Sliced Chicken 6 Inch Sandwich",
  servingSize: 207,
  calories: 300,
  fat: 6.3,
  carbs: 41,
  protein: 20,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Sliced Chicken", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Chicken Teriyaki 6 Inch Sandwich",
  servingSize: 257,
  calories: 362,
  fat: 7.3,
  carbs: 46,
  protein: 27,
  source: "Subway",
  cuisine: "Asian Fusion",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Chicken Teriyaki", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Chicken Strips 6 Inch Sandwich",
  servingSize: 229,
  calories: 324,
  fat: 7.1,
  carbs: 39,
  protein: 25,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Chicken Strips", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Roasted Chicken Breast 6 Inch Sandwich",
  servingSize: 232,
  calories: 331,
  fat: 8.0,
  carbs: 41,
  protein: 23,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Roasted Chicken Breast", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Ham 6 Inch Sandwich",
  servingSize: 221,
  calories: 317,
  fat: 7.3,
  carbs: 44,
  protein: 19,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Ham", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Italian Meatballs 6 Inch Sandwich",
  servingSize: 255,
  calories: 383,
  fat: 11.7,
  carbs: 47,
  protein: 20,
  source: "Subway",
  cuisine: "Italian-American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Italian Meatballs", "Marinara Sauce", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Roast Beef 6 Inch Sandwich",
  servingSize: 224,
  calories: 346,
  fat: 7.1,
  carbs: 40,
  protein: 21,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Roast Beef", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Taco Beef 6 Inch Sandwich",
  servingSize: 211,
  calories: 320,
  fat: 8.9,
  carbs: 42,
  protein: 17,
  source: "Subway",
  cuisine: "Tex-Mex",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Taco Beef", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Italian B.M.T.™ 6 Inch Sandwich",
  servingSize: 229,
  calories: 409,
  fat: 16.7,
  carbs: 42,
  protein: 22,
  source: "Subway",
  cuisine: "Italian-American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Salami", "Pepperoni", "Ham", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Subway Club™ 6 Inch Sandwich",
  servingSize: 226,
  calories: 325,
  fat: 7.1,
  carbs: 41,
  protein: 21,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Turkey Breast", "Roast Beef", "Ham", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Subway Melt™ 6 Inch Sandwich",
  servingSize: 211,
  calories: 321,
  fat: 8.6,
  carbs: 42,
  protein: 18,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Turkey Breast", "Ham", "Bacon", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Tuna 6 Inch Sandwich",
  servingSize: 239,
  calories: 507,
  fat: 29.1,
  carbs: 39,
  protein: 22,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Tuna Salad", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Shrimp 6 Inch Sandwich",
  servingSize: 186,
  calories: 266,
  fat: 5.7,
  carbs: 39,
  protein: 10,
  source: "Subway",
  cuisine: "Seafood",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Shrimp", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Avocado Shrimp 6 Inch Sandwich",
  servingSize: 221,
  calories: 340,
  fat: 12.7,
  carbs: 42,
  protein: 11,
  source: "Subway",
  cuisine: "Seafood",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Shrimp", "Avocado", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Egg Mayo 6 Inch Sandwich",
  servingSize: 225,
  calories: 421,
  fat: 20.7,
  carbs: 41,
  protein: 17,
  source: "Subway",
  cuisine: "American",
  isVegetarian: true,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Egg Mayonnaise", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Veggie Delight™ 6 Inch Sandwich",
  servingSize: 165,
  calories: 250,
  fat: 5.7,
  carbs: 39,
  protein: 10,
  source: "Subway",
  cuisine: "American",
  isVegetarian: true,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Diced Beef 6 Inch Sandwich",
  servingSize: 236,
  calories: 366,
  fat: 10.6,
  carbs: 40,
  protein: 26,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Diced Beef", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Falafel 6 Inch Sandwich",
  servingSize: 240,
  calories: 425,
  fat: 13.2,
  carbs: 58,
  protein: 16,
  source: "Subway",
  cuisine: "Middle Eastern",
  isVegetarian: true,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Falafel", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Angus Beef 6 Inch Sandwich",
  servingSize: 238,
  calories: 412,
  fat: 16.1,
  carbs: 44,
  protein: 22,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Angus Beef", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Spicy Chicken Strips 6 Inch Sandwich",
  servingSize: 255,
  calories: 369,
  fat: 7.1,
  carbs: 48,
  protein: 28,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Spicy Chicken Strips", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Sichuan Pepper Chicken 6 Inch Sandwich",
  servingSize: 246,
  calories: 379,
  fat: 14.0,
  carbs: 36,
  protein: 24,
  source: "Subway",
  cuisine: "Asian Fusion",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Wheat Bread", "Sichuan Pepper Chicken", "Lettuce", "Tomatoes", "Cucumber", "Green Peppers", "Onions", "American Cheese"]
},

{
  name: "Sliced Chicken Salad",
  servingSize: 346,
  calories: 143,
  fat: 5.1,
  carbs: 12,
  protein: 14,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Sliced Chicken", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Chicken Teriyaki Salad",
  servingSize: 396,
  calories: 205,
  fat: 6.2,
  carbs: 17,
  protein: 22,
  source: "Subway",
  cuisine: "Asian Fusion",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Chicken Teriyaki", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Chicken Strips Salad",
  servingSize: 368,
  calories: 167,
  fat: 5.9,
  carbs: 10,
  protein: 20,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Chicken Strips", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Roasted Chicken Breast Salad",
  servingSize: 371,
  calories: 174,
  fat: 6.9,
  carbs: 13,
  protein: 17,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Roasted Chicken Breast", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Ham Salad",
  servingSize: 360,
  calories: 159,
  fat: 6.2,
  carbs: 15,
  protein: 13,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Ham", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Italian Meatballs Salad",
  servingSize: 394,
  calories: 226,
  fat: 10.6,
  carbs: 18,
  protein: 14,
  source: "Subway",
  cuisine: "Italian-American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Italian Meatballs", "Marinara Sauce", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Roast Beef Salad",
  servingSize: 363,
  calories: 189,
  fat: 5.9,
  carbs: 11,
  protein: 16,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Roast Beef", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Taco Beef Salad",
  servingSize: 350,
  calories: 163,
  fat: 7.8,
  carbs: 13,
  protein: 12,
  source: "Subway",
  cuisine: "Tex-Mex",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Taco Beef", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Italian B.M.T.™ Salad",
  servingSize: 368,
  calories: 252,
  fat: 15.5,
  carbs: 13,
  protein: 17,
  source: "Subway",
  cuisine: "Italian-American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Salami", "Pepperoni", "Ham", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Subway Club™ Salad",
  servingSize: 365,
  calories: 168,
  fat: 6.0,
  carbs: 13,
  protein: 15,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Turkey Breast", "Roast Beef", "Ham", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Subway Melt™ Salad",
  servingSize: 350,
  calories: 163,
  fat: 7.5,
  carbs: 13,
  protein: 13,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Turkey Breast", "Ham", "Bacon", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Tuna Salad",
  servingSize: 378,
  calories: 350,
  fat: 28.0,
  carbs: 10,
  protein: 16,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Tuna Salad", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Shrimp Salad",
  servingSize: 325,
  calories: 108,
  fat: 4.6,
  carbs: 10,
  protein: 5,
  source: "Subway",
  cuisine: "Seafood",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Shrimp", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Avocado Shrimp Salad",
  servingSize: 360,
  calories: 183,
  fat: 11.6,
  carbs: 13,
  protein: 5,
  source: "Subway",
  cuisine: "Seafood",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Shrimp", "Avocado", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Egg Mayo Salad",
  servingSize: 364,
  calories: 264,
  fat: 19.6,
  carbs: 13,
  protein: 11,
  source: "Subway",
  cuisine: "American",
  isVegetarian: true,
  isVegan: false,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Egg Mayonnaise", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Veggie Delight™ Salad",
  servingSize: 304,
  calories: 93,
  fat: 4.5,
  carbs: 10,
  protein: 5,
  source: "Subway",
  cuisine: "American",
  isVegetarian: true,
  isVegan: true,
  isGlutenFree: true,
  isDairyFree: false,
  ingredients: ["Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Chicken Strip Energy Bowl Salad",
  servingSize: 359,
  calories: 276,
  fat: 12.9,
  carbs: 21,
  protein: 21,
  source: "Subway",
  cuisine: "American",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Chicken Strips", "Brown Rice", "Quinoa", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Falafel Energy Bowl Salad",
  servingSize: 370,
  calories: 404,
  fat: 23.9,
  carbs: 33,
  protein: 13,
  source: "Subway",
  cuisine: "Middle Eastern",
  isVegetarian: true,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Falafel", "Brown Rice", "Quinoa", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
{
  name: "Taco Beef Energy Bowl Salad",
  servingSize: 341,
  calories: 362,
  fat: 26.5,
  carbs: 15,
  protein: 18,
  source: "Subway",
  cuisine: "Tex-Mex",
  isVegetarian: false,
  isVegan: false,
  isGlutenFree: false,
  isDairyFree: false,
  ingredients: ["Taco Beef", "Brown Rice", "Quinoa", "Lettuce", "Tomatoes", "Cucumbers", "Green Peppers", "Onions", "American Cheese"]
},
  
  // Chipotle items
{
    name: "High-Protein Burrito for Muscle Gain",
    servingSize: 970, // approximate total weight in grams
    calories: 1460,
    fat: 67,
    carbs: 129,
    protein: 84,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: [
      "Tortilla",
      "Chicken",
      "Steak",
      "White Rice",
      "Black Beans",
      "Cheese",
      "Sour Cream",
      "Guacamole",
      "Fajita Veggies"
    ]
  },
  {
    name: "Vegetarian Burrito for Weight Loss",
    servingSize: 600, // approximate total weight in grams
    calories: 520,
    fat: 19,
    carbs: 69,
    protein: 17,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: [
      "Tortilla",
      "Sofritas",
      "No Rice",
      "No Beans",
      "Fajita Veggies",
      "Fresh Tomato Salsa",
      "Romaine Lettuce"
    ]
  },
  {
    name: "Balanced Burrito for Maintenance",
    servingSize: 800, // approximate total weight in grams
    calories: 970,
    fat: 32,
    carbs: 115,
    protein: 50,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: [
      "Tortilla",
      "Beef Barbacoa",
      "Brown Rice",
      "Pinto Beans",
      "Cheese",
      "Fresh Tomato Salsa",
      "Romaine Lettuce"
    ]
  },
  {
    name: "Vegan Burrito",
    servingSize: 850, // approximate total weight in grams
    calories: 1140,
    fat: 51,
    carbs: 146,
    protein: 34,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: [
      "Tortilla",
      "Sofritas",
      "Brown Rice",
      "Black Beans",
      "Fajita Veggies",
      "Roasted Chili-Corn Salsa",
      "Guacamole"
    ]
  },
  {
    name: "Low-Carb Burrito Bowl for Weight Loss",
    servingSize: 500, // approximate total weight in grams
    calories: 335,
    fat: 13,
    carbs: 13,
    protein: 54,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: [
      "No Tortilla",
      "Chicken",
      "No Rice",
      "No Beans",
      "Fajita Veggies",
      "Tomatillo-Red Chili Salsa",
      "Romaine Lettuce",
      "Extra Chicken"
    ]
  },
  {
    name: "Gluten-Free Burrito",
    servingSize: 750, // approximate total weight in grams
    calories: 1015,
    fat: 59,
    carbs: 90,
    protein: 43,
    source: "Custom Burrito",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true, // Assuming corn tortilla is used
    isDairyFree: false,
    ingredients: [
      "Corn Tortilla",
      "Carnitas",
      "White Rice",
      "Pinto Beans",
      "Cheese",
      "Tomatillo-Green Chili Salsa",
      "Guacamole"
    ]
  },
  {
    name: "Chicken Burrito Bowl",
    servingSize: 510,
    calories: 510,
    fat: 17.5,
    carbs: 40,
    protein: 50,
    source: "Chipotle",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Chicken", "Rice", "Beans", "Salsa", "Lettuce"]
  },
  {
    name: "Steak Burrito Bowl",
    servingSize: 480,
    calories: 480,
    fat: 16.5,
    carbs: 41,
    protein: 39,
    source: "Chipotle",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Steak", "Rice", "Beans", "Salsa", "Lettuce"]
  },
  {
    name: "Barbacoa Burrito Bowl",
    servingSize: 500,
    calories: 500,
    fat: 17.5,
    carbs: 42,
    protein: 42,
    source: "Chipotle",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Barbacoa", "Rice", "Beans", "Salsa", "Lettuce"]
  },
  {
    name: "Low Carb Chicken Burrito Bowl",
    servingSize: 370,
    calories: 370,
    fat: 16,
    carbs: 18,
    protein: 42,
    source: "Chipotle",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Chicken", "Lettuce", "Salsa", "Guacamole"]
  },
  {
    name: "Chicken Salad",
    servingSize: 490,
    calories: 490,
    fat: 11,
    carbs: 57,
    protein: 48,
    source: "Chipotle",
    cuisine: "Mexican",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Chicken", "Lettuce", "Beans", "Salsa", "Guacamole"]
  },

  {
    name: "Chicken Barbacoa Market Bowl",
    servingSize: 400,
    calories: 400,
    fat: 23,
    carbs: 33,
    protein: 19,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Chicken", "Barbacoa Sauce", "Rice", "Beans", "Lettuce"]
  },
  {
    name: "Forager's Warm Bowl",
    servingSize: 630,
    calories: 630,
    fat: 29,
    carbs: 79,
    protein: 25,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Quinoa", "Sweet Potatoes", "Mushrooms", "Kale", "Cheese"]
  },
  {
    name: "Keto Zoodle Bowl",
    servingSize: 440,
    calories: 440,
    fat: 32,
    carbs: 14,
    protein: 34,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Zoodles", "Chicken", "Almonds", "Avocado", "Dressing"]
  },
  {
    name: "Buffalo Chicken Wrap",
    servingSize: 560,
    calories: 560,
    fat: 21,
    carbs: 61,
    protein: 34,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Chicken", "Buffalo Sauce", "Tortilla", "Cheese", "Lettuce"]
  },
  {
    name: "Spicy Chicken Caesar Wrap",
    servingSize: 570,
    calories: 570,
    fat: 20,
    carbs: 62,
    protein: 38,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Chicken", "Caesar Dressing", "Tortilla", "Cheese", "Lettuce"]
  },
  {
    name: "Avo Blast Toast",
    servingSize: 450,
    calories: 450,
    fat: 27,
    carbs: 51,
    protein: 8,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Avocado", "Bread", "Chili Flakes", "Olive Oil", "Salt"]
  },
  {
    name: "Peanut Butter Warrior Smoothie",
    servingSize: 300,
    calories: 300,
    fat: 7,
    carbs: 55,
    protein: 37,
    source: "Just Salad",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Peanut Butter", "Banana", "Almond Milk", "Protein Powder"]
  },

  // Panera Bread items
  {
    name: "Asiago Cheese Bagel",
    servingSize: 113,
    calories: 320,
    fat: 5,
    carbs: 55,
    protein: 14,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Enriched Wheat Flour", "Water", "Asiago Cheese", "Salt", "Yeast"]
  },
  {
    name: "Blueberry Bagel",
    servingSize: 113,
    calories: 290,
    fat: 1,
    carbs: 61,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Blueberries", "Sugar", "Yeast", "Salt"]
  },
  {
    name: "Chocolate Chip Bagel",
    servingSize: 113,
    calories: 330,
    fat: 5,
    carbs: 60,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Enriched Wheat Flour", "Water", "Chocolate Chips", "Sugar", "Yeast", "Salt"]
  },
  {
    name: "Cinnamon Crunch Bagel",
    servingSize: 113,
    calories: 430,
    fat: 7,
    carbs: 82,
    protein: 9,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Enriched Wheat Flour", "Water", "Sugar", "Cinnamon Sugar Topping", "Yeast", "Salt"]
  },
  {
    name: "Cinnamon Swirl & Raisin Bagel",
    servingSize: 113,
    calories: 320,
    fat: 1.5,
    carbs: 65,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Raisins", "Sugar", "Cinnamon", "Yeast", "Salt"]
  },
  {
    name: "Everything Bagel",
    servingSize: 113,
    calories: 290,
    fat: 1.5,
    carbs: 58,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Poppy Seeds", "Sesame Seeds", "Onion", "Garlic", "Yeast", "Salt"]
  },
  {
    name: "Jalapeño Cheddar Bagel",
    servingSize: 113,
    calories: 300,
    fat: 3,
    carbs: 56,
    protein: 13,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Enriched Wheat Flour", "Water", "Cheddar Cheese", "Jalapeños", "Yeast", "Salt"]
  },
  {
    name: "Multigrain Bagel Flat",
    servingSize: 85,
    calories: 180,
    fat: 3,
    carbs: 32,
    protein: 7,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Whole Wheat Flour", "Water", "Grains", "Seeds", "Yeast", "Salt"]
  },
  {
    name: "Plain Bagel",
    servingSize: 113,
    calories: 280,
    fat: 1,
    carbs: 57,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Yeast", "Salt"]
  },
  {
    name: "Poppyseed Bagel",
    servingSize: 113,
    calories: 290,
    fat: 2,
    carbs: 58,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Poppy Seeds", "Yeast", "Salt"]
  },
  {
    name: "Salt Bagel",
    servingSize: 113,
    calories: 280,
    fat: 1,
    carbs: 57,
    protein: 10,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Salt", "Yeast"]
  },
  {
    name: "Sesame Bagel",
    servingSize: 113,
    calories: 290,
    fat: 2.5,
    carbs: 58,
    protein: 11,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Sesame Seeds", "Yeast", "Salt"]
  },
  {
    name: "French Baguette",
    servingSize: 57,
    calories: 150,
    fat: 0,
    carbs: 30,
    protein: 5,
    source: "Panera Bread",
    cuisine: "French",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Unbleached Enriched Wheat Flour", "Water", "Yeast", "Salt"]
  },
  {
    name: "Artisan Ciabatta",
    servingSize: 57,
    calories: 150,
    fat: 1.5,
    carbs: 30,
    protein: 6,
    source: "Panera Bread",
    cuisine: "Italian",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Unbleached Enriched Wheat Flour", "Water", "Olive Oil", "Yeast", "Salt"]
  },
  {
    name: "Brioche Roll",
    servingSize: 70,
    calories: 210,
    fat: 7,
    carbs: 31,
    protein: 8,
    source: "Panera Bread",
    cuisine: "French",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Enriched Wheat Flour", "Eggs", "Butter", "Sugar", "Yeast", "Salt"]
  },
  {
    name: "Classic Sourdough",
    servingSize: 57,
    calories: 150,
    fat: 0,
    carbs: 31,
    protein: 6,
    source: "Panera Bread",
    cuisine: "French",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Unbleached Enriched Wheat Flour", "Water", "Sourdough Starter", "Salt"]
  },
  {
    name: "Tomato Basil Miche",
    servingSize: 57,
    calories: 130,
    fat: 0,
    carbs: 27,
    protein: 5,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Enriched Wheat Flour", "Water", "Tomato", "Basil", "Yeast", "Salt"]
  },
  {
    name: "White Whole Grain",
    servingSize: 57,
    calories: 130,
    fat: 0.5,
    carbs: 25,
    protein: 6,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    ingredients: ["Whole Wheat Flour", "Water", "Yeast", "Salt"]
  },
  {
    name: "Avocado, Egg White, Spinach & Cheese on Multigrain Bagel Flat",
    servingSize: 1,
    calories: 340,
    fat: 14,
    carbs: 36,
    protein: 19,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Multigrain Bagel Flat", "Egg Whites", "Avocado", "Spinach", "Cheddar Cheese"]
  },
  {
    name: "Bacon, Egg & Cheese on Brioche",
    servingSize: 1,
    calories: 450,
    fat: 26,
    carbs: 33,
    protein: 24,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    ingredients: ["Brioche Roll", "Bacon", "Egg", "Cheddar Cheese"]
  },
  {
    name: "Steel Cut Oatmeal with Strawberries, Pecans & Cinnamon Crunch Topping",
    servingSize: 1,
    calories: 360,
    fat: 15,
    carbs: 52,
    protein: 8,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Steel Cut Oats", "Strawberries", "Pecans", "Cinnamon Crunch Topping"]
  },
  {
    name: "Steel Cut Oatmeal with Strawberries & Cinnamon Crunch Topping",
    servingSize: 1,
    calories: 260,
    fat: 4,
    carbs: 50,
    protein: 7,
    source: "Panera Bread",
    cuisine: "American",
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    ingredients: ["Steel Cut Oats", "Strawberries", "Cinnamon Crunch Topping"]
  }

];

export default combinedFoodDatabase;
